name: Check if newly added TeX files is compilable
on: [pull_request, issue_comment]
jobs:
  check_if_compilable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1
        with:
          files: |
            **/*.tex
            
      - name: Compile changed LaTeX files
        id: compile_tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: steps.changed-files.outputs.all_changed_files
          pre_compile: |
            curl -H 'Authorization: token ${{ secrets.SECRET_TOKEN }}' \
            -H 'Accept: application/vnd.github.v4.raw' \
            -O -L https://api.github.com/repos/cosmsstar/templates/contents/answer.cls \
            -O -L https://api.github.com/repos/cosmsstar/templates/contents/question.cls \
            -O -L https://api.github.com/repos/cosmsstar/templates/contents/pyp_base.cls \
            -O -L https://api.github.com/repos/cosmsstar/templates/contents/fonts
          extra_fonts: |
            fonts/*.ttf
            fonts/*.otf
          latexmk_use_xelatex: true
        env:
          TEXINPUTS: "./"
