name: Check if newly added TeX files is compilable
on: pull_request
jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1
        with:
          separator: "\n"
          files: |
            **/*.tex
      
      - name: Process files as multi-line string
#         run: |
#           FILES="${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
#           FILES=$(echo $FILES | tr " " "\n")
#           echo "FILES="$FILES"" >> $GITHUB_ENV
#           echo -e "$FILES"
        run: echo "${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
      
    outputs:
      changedTexFiles: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
            
  compile_new_tex_files:
    runs-on: ubuntu-latest
    needs: get_changed_files
    if: "${{ needs.get_changed_files.outputs.changedTexFiles != '' }}"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Compile changed LaTeX files
        id: compile_tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ needs.get_changed_files.outputs.changedTexFiles }}
          extra_fonts: |
            ./fonts/*.ttf
            ./fonts/*.otf
          latexmk_use_xelatex: true
        env:
          TEXINPUTS: "./"
